SELECT TOP (1000) [region]
      ,[price]
      ,[year]
      ,[manufacturer]
      ,[model]
      ,[condition]
      ,[cylinders]
      ,[fuel]
      ,[odometer]
      ,[title_status]
      ,[transmission]
      ,[description]
      ,[county]
      ,[state]
      ,[posting_date]
      ,[removal_date]
  FROM [CapstoneProject].[dbo].[craigslist_vehicles2]
